version: "3.7"

services:
  frontend:
    image: yagcis/fortune-cookie-frontend
    environment:
      BACKEND_DNS: backend
    ports:
    - "8080:8080"
  backend:
    image: yagcis/fortune-cookie-backend
    environment:
      REDIS_DNS: database
  database:
    image: redis
