name: go_frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Test
      run: cd frontend && go test
  Build-Push-Docker:
    runs-on: self-hosted
    needs: [Test]
    steps:
    - uses: actions/checkout@v2
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push - Frontend
      uses: docker/build-push-action@v2
      with:
        context: frontend
        push: true
        tags: yagcis/fortune-cookie-frontend:latest
    - name: Build and push - Backend
      uses: docker/build-push-action@v2
      with:
        context: backend
        push: true
        tags: yagcis/fortune-cookie-backend:latest